### ISSUE TITLE
Running on WebContainers returns unexpected token

### ISSUE THREAD

**Issue by FossPrime** [kentcdodds/cloc#24]
vite.new/vue-ts

```
❯ npx cloc
success Install finished in 4.635s

SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:29880)
    at _0x31d04f (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:143418)
    at _0x17c001._compile (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:141884)
    at _0x4e8c34 (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:138719)
    at Object.compileFunction (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:341449)
    at wrapSafe (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:218347)
    at Module._compile (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:218715)
    at Module._extensions..js (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:219743)
    at Module.load (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:217769)
    at Module._load (https://playground.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:215340)

```

**Comment by so1ve** [comment]
This is the correct behavior. Web container is a mini operator system for node only, but the `cloc` package is shipped with a prebuilt binary. Webcontainer mocks a node.js runtime in the browser and has a built-in virtual fs, but it is obviously not a `web linux`. It can run js / wasm files only, not binary files.
